name: Build

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}/${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: none
  deployments: none
  actions: none
  checks: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
  attestations: none
  models: none

jobs:
  parse-tag:
    name: Parse Tag
    runs-on: ubuntu-latest
    container:
      image: docker.io/oven/bun:1

    outputs:
      tag: ${{ steps.parse-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Parse Tag
        id: parse-tag
        run: |-
          bun parse-tag.mjs ${{ github.ref_name }}
          echo "tag=$(cat tag.txt)" >> $GITHUB_OUTPUT

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    needs:
      - parse-tag

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: xo/dbtpl
          ref: v${{ needs.parse-tag.outputs.tag }}
          fetch-depth: 0
          fetch-tags: true
          path: xo
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          show-progress: true

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          show-progress: true

      - name: Check if current tag is latest
        id: is-latest
        run: |
          latest_tag=$(git -C xo tag --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          echo "Latest tag: $latest_tag"

          current_tag="${{ needs.parse-tag.outputs.tag }}"
          echo "Current tag: $current_tag"

          if [ "$current_tag" = "$latest_tag" ]; then
            echo "is_latest=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_latest=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |-
            ghcr.io/${{ github.repository }}
          tags: |-
            type=raw,value=${{ needs.parse-tag.outputs.tag }},prefix=v,enabled=true
          flavor: |-
            # See https://github.com/docker/metadata-action#latest-tag
            latest=${{ github.ref_name == github.event.repository.default_branch }}
            prefix=,onlatest=false
          labels: |-
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.authors=${{ github.repository_owner }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Image Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          pull: true
          context: .
          file: Dockerfile
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
        timeout-minutes: 20
